version: "3"

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT:-80}
        - SSL_PORT=${SSL_PORT:-443}
        - SERVER_NAME=${SERVER_NAME:-localhost}
    ports:
      - ${PORT:-80}:80
      - ${SSL_PORT:-443}:443
    environment:
      - PORT=${PORT:-80}
      - SSL_PORT=${SSL_PORT:-443}
      - SERVER_NAME=${SERVER_NAME:-localhost}
    volumes:
      - ${SSL_CERTIFICATE_PATH:?err}:/etc/nginx/ssl/cert.pem
      - ${SSL_KEY_PATH:?err}:/etc/nginx/ssl/key.pem
      - ${SSL_CHAIN_PATH:?err}:/etc/nginx/ssl/chain.pem
